# Generated by Django 4.1.3 on 2022-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="starttime", field=models.DateTimeField(null=True),
        ),
    ]
