# Generated by Django 4.1.3 on 2022-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_movie_starttime"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="starttime",),
        migrations.AddField(
            model_name="movie",
            name="numofmin",
            field=models.IntegerField(default=144),
            preserve_default=False,
        ),
    ]
