# Generated by Django 4.1.3 on 2022-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_movie_starttime_movie_numofmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("movie", models.CharField(max_length=255)),
                ("numofseats", models.IntegerField()),
                ("phonenumber", models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="numofseats",
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie", name="description", field=models.TextField(),
        ),
    ]
