# Generated by Django 4.1.3 on 2022-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_viewer_movie_numofseats_alter_movie_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imgurl2",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
