# Generated by Django 3.2.16 on 2022-11-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movie_imgurl2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imgurl',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imgurl2',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
