# Generated by Django 4.1.3 on 2022-11-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20221128_2254"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="Christopher Nolan", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.CharField(default="2003", max_length=4),
            preserve_default=False,
        ),
    ]
