# Generated by Django 4.0.5 on 2022-11-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movie_director_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
            preserve_default=False,
        ),
    ]
