# Generated by Django 4.0.5 on 2022-11-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_movie_id_alter_viewer_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='movie_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='app.movie'),
        ),
    ]
