# Generated by Django 4.0.5 on 2022-11-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_viewer_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='movie_id',
            field=models.CharField(max_length=1000),
        ),
    ]
