# Generated by Django 4.1.3 on 2022-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_viewer_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewer",
            name="phonenumber",
            field=models.CharField(max_length=11),
        ),
    ]
